_wandb:
    value:
        cli_version: 0.22.3
        e:
            injzcylwesettjb6phc9puyuq8gh7nkv:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: /Users/rohit/Desktop/College/NEU/MLops/Labs/Lab2.ipynb
                codePathLocal: Lab2.ipynb
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "253368836096"
                email: rohit.kandiraju@gmail.com
                executable: /Users/rohit/Desktop/College/NEU/MLops/Labs/.venv/bin/python
                git:
                    commit: 757d14d17d0d53426e7c9499b4836e9f23fce548
                    remote: https://github.com/ManoghnK/MLOps_LabAssignments.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/rohit/Desktop/College/NEU/MLops/Labs/Lab2.ipynb
                python: CPython 3.11.13
                root: /Users/rohit/Desktop/College/NEU/MLops/Labs
                startedAt: "2025-11-04T03:10:11.067306Z"
                writerId: injzcylwesettjb6phc9puyuq8gh7nkv
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
            - "2": batch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 7
                - 13
                - 16
                - 38
                - 39
                - 61
            "4": 3.11.13
            "5": 0.22.3
            "8":
                - 1
            "12": 0.22.3
            "13": darwin-arm64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
dropout:
    value: 0.2
epochs:
    value: 5
layer_1_size:
    value: 32
learn_rate:
    value: 0.01
momentum:
    value: 0.9
sample:
    value: 10000
